### ISSUE TITLE
There is an error at Function "run_rmtlr & rmtlr_test"

### ISSUE THREAD

**Issue by Jin0331** [olapuentesantana/mechanistic_biomarkers_immuno-oncology#2]
# perform prediction
  prediction_cv <- lapply(coef_values, function(X){**rmtlr_test**(prediction.X, X)})

---> 
fit.pred <- t(matrix(as.matrix(Intercept), nrow = ncol(Slope), ncol = nrow(x.test.combo))
                  + t(Slope) %*% t(as.matrix(x.test.combo[,rownames(Slope)])))

In the code above,

 Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': error in evaluating the argument 'x' in selecting a method for function 't': error in evaluating the argument 'x' in selecting a method for function 'as.matrix': undefined columns selected

**Comment by olapuentesantana** [comment]
Hi,

Could you provide more info about your error? e.g. How do the variables "coef_values" and "prediction.X" look like?

Cheers,
Óscar
